# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Tests

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
               
    - name: Test Execution
      run: mvn -B -X clean test -Dmaven.test.failure.ignore=true --file pom.xml
                 
    - name: Attach TestSuite
      uses: actions/upload-artifact@v2
      with:
        name: TEST-TestSuite.xml
        path: "target/surefire-reports/TEST-TestSuite.xml"

  
  analize:
    if: always()
    name: Analize test result
    runs-on: ubuntu-latest
    # Only run this workflow when "build" workflow succeeds
    needs: [test]
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
    
    steps:
      - name: Download TEST-TestSuite.xml
        uses: actions/download-artifact@v3
        with:
          name: TEST-TestSuite.xml
      
      #required for step Test Reporter - WA fatal: not a git repository (or any of the parent directories): .git
      - name: Run git init
        run: git init
      
      - name: Test Reporter
        id: testreport
        uses: dorny/test-reporter@v1.4.3
        with:
          name: Run Tests
          path: "TEST-TestSuite.xml"
          reporter: java-junit
          fail-on-error: true
